### ISSUE TITLE
(AUR) Comply with rust package guidelines

### ISSUE THREAD

**Issue by arthurbacci** [noahra/byteblitz#58]
It makes it easier for Arch Linux users to install and update byteblitz.

**Comment by arthurbacci** [comment]
`byteblitz` seems to be working.

**Comment by arthurbacci** [comment]
Arch has some [guidelines for Rust packages](https://wiki.archlinux.org/title/Rust_package_guidelines) that should probably be followed.

**Comment by arthurbacci** [comment]
Also, may be interesting to create `byteblitz-git` to get the latest commit. And removing git from the dependencies of the release package (it doesn't seem to be using it)

**Comment by noahra** [comment]
> Arch has some [guidelines for Rust packages](https://wiki.archlinux.org/title/Rust_package_guidelines) that should probably be followed.

The PKGBUILD is now compliant with the guidelines. `byteblitz-git` will be added in the future, but it is not a priority at the moment.
